/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PromptArchive API
 * REST API for storing and managing prompts (Go + Gin + PostgreSQL + Redis)
 * OpenAPI spec version: 1.0
 */
import type { GetPromptsIdVersions200AllOfData } from './getPromptsIdVersions200AllOfData';

export type GetPromptsIdVersions200AllOf = {
  data?: GetPromptsIdVersions200AllOfData;
};
