/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PromptArchive API
 * REST API for storing and managing prompts (Go + Gin + PostgreSQL + Redis)
 * OpenAPI spec version: 1.0
 */
import type { InternalHandlerResponse } from './internalHandlerResponse';
import type { GetPromptsId200AllOf } from './getPromptsId200AllOf';

export type GetPromptsId200 = InternalHandlerResponse & GetPromptsId200AllOf;
