/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PromptArchive API
 * REST API for storing and managing prompts (Go + Gin + PostgreSQL + Redis)
 * OpenAPI spec version: 1.0
 */
import type { GetPublicPromptsSort } from './getPublicPromptsSort';

export type GetPublicPromptsParams = {
/**
 * Page number
 */
page?: number;
/**
 * Items per page
 * @maximum 100
 */
per_page?: number;
/**
 * Sort field
 */
sort?: GetPublicPromptsSort;
/**
 * Search in title and content
 */
search?: string;
};
