/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PromptArchive API
 * REST API for storing and managing prompts (Go + Gin + PostgreSQL + Redis)
 * OpenAPI spec version: 1.0
 */

export type GetPublicPromptsSort = typeof GetPublicPromptsSort[keyof typeof GetPublicPromptsSort];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetPublicPromptsSort = {
  created_at: 'created_at',
  '-created_at': '-created_at',
  likes_count: 'likes_count',
  '-likes_count': '-likes_count',
} as const;
