/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PromptArchive API
 * REST API for storing and managing prompts (Go + Gin + PostgreSQL + Redis)
 * OpenAPI spec version: 1.0
 */
import type { GetPromptsSort } from './getPromptsSort';
import type { GetPromptsVisibility } from './getPromptsVisibility';

export type GetPromptsParams = {
/**
 * Page number
 */
page?: number;
/**
 * Items per page
 * @maximum 100
 */
per_page?: number;
/**
 * Sort field
 */
sort?: GetPromptsSort;
/**
 * Filter by visibility
 */
visibility?: GetPromptsVisibility;
/**
 * Filter by folder ID (UUID)
 */
folder_id?: string;
/**
 * Filter by tag IDs (comma-separated UUIDs)
 */
tag_ids?: string;
/**
 * Search in title and content
 */
search?: string;
};
