/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PromptArchive API
 * REST API for storing and managing prompts (Go + Gin + PostgreSQL + Redis)
 * OpenAPI spec version: 1.0
 */

export type GetPromptsSort = typeof GetPromptsSort[keyof typeof GetPromptsSort];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetPromptsSort = {
  created_at: 'created_at',
  '-created_at': '-created_at',
  updated_at: 'updated_at',
  '-updated_at': '-updated_at',
  title: 'title',
  '-title': '-title',
  use_count: 'use_count',
  '-use_count': '-use_count',
} as const;
