/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PromptArchive API
 * REST API for storing and managing prompts (Go + Gin + PostgreSQL + Redis)
 * OpenAPI spec version: 1.0
 */
import type { GithubComIntocodePromptarchiveInternalServiceVersionResponse } from './githubComIntocodePromptarchiveInternalServiceVersionResponse';

export type GetPromptsIdVersions200AllOfData = {
  total?: number;
  versions?: GithubComIntocodePromptarchiveInternalServiceVersionResponse[];
};
