/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PromptArchive API
 * REST API for storing and managing prompts (Go + Gin + PostgreSQL + Redis)
 * OpenAPI spec version: 1.0
 */
import type { InternalHandlerResponse } from './internalHandlerResponse';
import type { GetSharedShareToken200AllOf } from './getSharedShareToken200AllOf';

export type GetSharedShareToken200 = InternalHandlerResponse & GetSharedShareToken200AllOf;
