/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PromptArchive API
 * REST API for storing and managing prompts (Go + Gin + PostgreSQL + Redis)
 * OpenAPI spec version: 1.0
 */
import type { GithubComIntocodePromptarchiveInternalServiceAuthorSummary } from './githubComIntocodePromptarchiveInternalServiceAuthorSummary';

export interface GithubComIntocodePromptarchiveInternalServicePublicPromptDetail {
  author?: GithubComIntocodePromptarchiveInternalServiceAuthorSummary;
  content?: string;
  created_at?: string;
  description?: string;
  id?: string;
  is_liked?: boolean;
  likes_count?: number;
  title?: string;
  use_count?: number;
  view_count?: number;
}
