/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PromptArchive API
 * REST API for storing and managing prompts (Go + Gin + PostgreSQL + Redis)
 * OpenAPI spec version: 1.0
 */
import type { GithubComIntocodePromptarchiveInternalServiceFolderSummary } from './githubComIntocodePromptarchiveInternalServiceFolderSummary';
import type { GithubComIntocodePromptarchiveInternalServiceTagSummary } from './githubComIntocodePromptarchiveInternalServiceTagSummary';

export interface GithubComIntocodePromptarchiveInternalServicePromptResponse {
  content?: string;
  created_at?: string;
  description?: string;
  folder?: GithubComIntocodePromptarchiveInternalServiceFolderSummary;
  id?: string;
  share_token?: string;
  tags?: GithubComIntocodePromptarchiveInternalServiceTagSummary[];
  title?: string;
  updated_at?: string;
  use_count?: number;
  /** Always 0 until Iteration 4 */
  version_count?: number;
  view_count?: number;
  visibility?: string;
}
