/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PromptArchive API
 * REST API for storing and managing prompts (Go + Gin + PostgreSQL + Redis)
 * OpenAPI spec version: 1.0
 */
import type { GithubComIntocodePromptarchiveInternalServiceVariableInfo } from './githubComIntocodePromptarchiveInternalServiceVariableInfo';

export interface GithubComIntocodePromptarchiveInternalServiceVariablesResponse {
  has_variables?: boolean;
  variables?: GithubComIntocodePromptarchiveInternalServiceVariableInfo[];
}
