/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PromptArchive API
 * REST API for storing and managing prompts (Go + Gin + PostgreSQL + Redis)
 * OpenAPI spec version: 1.0
 */
import type { InternalHandlerError } from './internalHandlerError';
import type { InternalHandlerMeta } from './internalHandlerMeta';

export interface InternalHandlerResponse {
  data?: unknown;
  error?: InternalHandlerError;
  meta?: InternalHandlerMeta;
  success?: boolean;
}
