/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PromptArchive API
 * REST API for storing and managing prompts (Go + Gin + PostgreSQL + Redis)
 * OpenAPI spec version: 1.0
 */

export interface InternalHandlerCreateFolderRequest {
  color?: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string;
}
