/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PromptArchive API
 * REST API for storing and managing prompts (Go + Gin + PostgreSQL + Redis)
 * OpenAPI spec version: 1.0
 */

export type InternalHandlerCreatePromptRequestVisibility = typeof InternalHandlerCreatePromptRequestVisibility[keyof typeof InternalHandlerCreatePromptRequestVisibility];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InternalHandlerCreatePromptRequestVisibility = {
  private: 'private',
  public: 'public',
  unlisted: 'unlisted',
} as const;
