/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PromptArchive API
 * REST API for storing and managing prompts (Go + Gin + PostgreSQL + Redis)
 * OpenAPI spec version: 1.0
 */
import type { InternalHandlerUpdatePromptRequestVisibility } from './internalHandlerUpdatePromptRequestVisibility';

export interface InternalHandlerUpdatePromptRequest {
  /**
   * @minLength 1
   * @maxLength 50000
   */
  content?: string;
  /** @maxLength 1000 */
  description?: string;
  folder_id?: string;
  tag_ids?: string[];
  /**
   * @minLength 1
   * @maxLength 200
   */
  title?: string;
  visibility?: InternalHandlerUpdatePromptRequestVisibility;
}
