/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PromptArchive API
 * REST API for storing and managing prompts (Go + Gin + PostgreSQL + Redis)
 * OpenAPI spec version: 1.0
 */
import type { PostPromptsIdUse200AllOfData } from './postPromptsIdUse200AllOfData';

export type PostPromptsIdUse200AllOf = {
  data?: PostPromptsIdUse200AllOfData;
};
